### ISSUE TITLE
Make packages publicly available

### ISSUE THREAD

**Issue by TheRealSpaceShip** [agilestacks/toolbox#10]
Current packages [hub-toolbox](https://github.com/orgs/epam/packages/container/package/hub-toolbox) and [hub-toolbox-gcp-cloud-shell](https://github.com/orgs/epam/packages/container/package/hub-toolbox-gcp-cloud-shell) need to make public.

**Comment by cm-howard** [comment]
To confirm that both packages have been made public. 👍🏼
