### ISSUE TITLE
Cloud Shell container build should fail if cannot download file

### ISSUE THREAD

**Issue by akranga** [agilestacks/toolbox#4]
Today cloud shell build downloads whatever `curl` commands returns.  Yet it should fail fast to give immediate feedback to the user who wants to build a container. Easiest way to fix is to add `--fail` flag to download  [see here](https://superuser.com/a/657174)

**Comment by akranga** [comment]
Any progress with this?

**Comment by oginskis** [comment]
I believe @TheRealSpaceShip fixed that with his recent commits to the toolbox: https://github.com/agilestacks/toolbox/commit/d2144df43fd79d0e8028c4106cfe0d153bbaf208#diff-63b2923975ca27c3e76896daa2f0605e0c4324719f847bbee4c764e6c5105858

**Comment by TheRealSpaceShip** [comment]
I will recheck some cases with tools that downloaded as binary
