### ISSUE TITLE
Outdated helm in shell-box

### ISSUE THREAD

**Issue by akranga** [agilestacks/toolbox#5]
Currently gcp shell helm extension throws folllowing error

Error: "helm repo update" accepts no arguments
 
Usage:  helm repo update [flags]

Which however contradicts to the actual synopsis of helm cli

See: https://helm.sh/docs/helm/helm_repo_update/

Quick solution to update helm to the latest actual version

**Comment by akranga** [comment]
Shell box was relying on out-dated `helm 3.5.0`. Currently we install `3.8.2` (same as for GCP toolbox). 

> Note latest current  helm version is `3.9.0`

**Comment by akranga** [comment]
Fix should be now available in: `gcr.io/superhub/cloud-shell:latest`

**Comment by mameshini** [comment]
That resolved the issue, I was able to deploy GKE sandbox without any errors.
