### ISSUE TITLE
GitHub Action should rely on latest release hub

### ISSUE THREAD

**Issue by akranga** [agilestacks/toolbox#6]
Update GH actions to rely on:

- [x] Latest release of hub
- [x] Latest release of hub-state
- [x] ~~Remove `image` script as superseded by GitHub actions~~

> Latest GH release can be fetched with API call:  https://docs.github.com/en/rest/releases/releases

**Comment by TheRealSpaceShip** [comment]
I think we should leave the `image` script as a backup solution in case there is some problem with GitHub actions
